# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='travel',
            name='start',
            field=models.DateField(),
        ),
    ]
