# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('travels', '0002_auto_20170726_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.Travel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
